### ISSUE TITLE
RMX3361

### ISSUE THREAD

**Issue by yuxuxin233** [R0rt1z2/realme-ota#14] opened 2022-02-23 07:02 UTC
![QQ图片20220223150016](https://user-images.githubusercontent.com/73999603/155274216-37471836-9db0-4865-b639-95b1209b1568.png)
realme-ota RMX3361 RMX3361_11.C.01_001_202202101618 3 -r 1

**Comment by yuxuxin233** [comment] 2022-02-23 07:08
realme-ota RMX3361 RMX3361_11.A.01_001_202202101618 3 -r 1

**Comment by R0rt1z2** [comment] 2022-05-09 08:55
Duplicate of https://github.com/R0rt1z2/realme-ota/issues/5.

**Closed by R0rt1z2** 2022-05-09 08:55 UTC
