### ISSUE TITLE
Received invalid response (artifactV1Result is empty)!

### ISSUE THREAD

**Issue by yuxuxin233** [R0rt1z2/realme-ota#8] opened 2022-01-14 07:47 UTC
![Screenshot_2022-01-14-15-44-35-916_com termux](https://user-images.githubusercontent.com/73999603/149470242-57f75b4e-92df-4177-8220-5b121b9257cf.jpg)

**Comment by yuxuxin233** [comment] 2022-01-16 11:31
![Screenshot_2022-01-16-18-44-10-426_com miui notes](https://user-images.githubusercontent.com/73999603/149658030-45738814-40f0-4cda-9eb5-86e5182d9895.jpg)
![Screenshot_2022-01-16-19-01-48-301_com termux](https://user-images.githubusercontent.com/73999603/149658035-6ad9921d-78e7-47ae-81d4-1d15ab36e6a5.jpg)
![Screenshot_2022-01-16-19-02-38-425_com termux](https://user-images.githubusercontent.com/73999603/149658037-f8a8f4e3-fbc2-4a16-a55c-2a20fb55d36c.jpg)
![Uploading -5649d95e1291d5a7.jpg…]()

**Comment by yuxuxin233** [comment] 2022-01-16 11:34
![-5649d95e1291d5a7](https://user-images.githubusercontent.com/73999603/149658169-fff6fc8f-d69f-41cf-91ed-3f5ecbb4b024.jpg)
![235fee709b732003](https://user-images.githubusercontent.com/73999603/149658172-8dbe8df4-a7a7-4e4f-b06e-04f22b05e19c.jpg)

**Comment by yuxuxin233** [comment] 2022-01-16 11:39
/my_manifest/divisional ro.build.version.ota=RMX2202_11.C.10_1100_202112161843Unable to get

**Comment by R0rt1z2** [comment] 2022-01-18 16:32
Duplicate of https://github.com/R0rt1z2/realme-ota/issues/5 I guess. @yuxuxin233 Has your device officially received the RealmeUI 3 (Android 12.0) update?

**Comment by yuxuxin233** [comment] 2022-01-18 22:47
yes

**Comment by R0rt1z2** [comment] 2022-02-18 15:11
Closing as per https://github.com/R0rt1z2/realme-ota/issues/5#issuecomment-1044675347

**Closed by R0rt1z2** 2022-02-18 15:11 UTC
